import { Geist, Geist_Mono } from "next/font/google";
import { headers } from 'next/headers'; // Import headers

import { AppSidebar } from "@/components/app-sidebar"
import { Breadcrumbs } from "@/components/breadcrumb";
import { Separator } from "@/components/ui/separator"
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar"
import { Toaster } from "@/components/ui/sonner"


import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  // const pathname = (await headers())
  // console.log(pathname)
  // const pathnames = pathname.split('/').filter(x => x); // Split the pathname and filter out empty strings

  return (
    <html lang="en">
      <body
      // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        (<SidebarProvider>
          <AppSidebar />
            <SidebarInset>
              <header
                className=" -mt-6 bg-neutral-50 border flex h-16 shrink-0 items-center gap-2 transition-[width,height] ease-linear group-has-data-[collapsible=icon]/sidebar-wrapper:h-12">
                <div className="flex items-center gap-2 px-4">
                  <SidebarTrigger className="-ml-1" />
                  <Separator orientation="vertical" className="mr-2 data-[orientation=vertical]:h-4" />
                  <Breadcrumbs />
                </div>
              </header>
              {children}
            </SidebarInset>
        </SidebarProvider>)
        <Toaster />
      </body>
    </html>
  );
}
